export default {
	GET_DATA: "GET_DATA",
	GET_RESPONSES: "GET_RESPONSES",
	HASLOADED: "HASLOADED",
	ISUPDATING: "ISUPDATING",
	HASUPDATED: "HASUPDATED",
	ADD_CARD: "ADD_CARD",
	ADD_DIALOGUE: "ADD_DIALOGUE",
	DELETE_CARD: "DELETE_CARD",
	DELETE_DIALOGUE: "DELETE_DIALOGUE",
	CHANGE_CARD: "CHANGE_CARD",
	CHANGE_DIALOGUE: "CHANGE_DIALOGUE",
	CHANGE_DIALOGUE_TITLE: "CHANGE_DIALOGUE_TITLE",
	CHANGE_DEVICE_POSITION: "CHANGE_DEVICE_POSITION",
	CHANGE_DEVICE_DIALOGUES: "CHANGE_DEVICE_DIALOGUES",
	ADD_DIALOGUE_DEVICE: "ADD_DIALOGUE_DEVICE",
	REMOVE_DIALOGUE_DEVICE: "REMOVE_DIALOGUE_DEVICE"
}